# Chapter 7: Armstrong {-}

Ender ran to the camera. He said,” Armstrong! he did that!”  

Armstrong flew over our base in his spaceship. Suddenly arms came out of the spaceship. One arm was holding a machine called “The Hypnotizer”

Meanwhile, I was being chased by Endy, Ave and King Zombie. Suddenly a slot opened in my Life Ship that was the same shape as the Life Sword. So I put the Life Sword in. Just then a giant sword formed on top of my spaceship. “Perfect.” I said. 

I fought the bad guys but they continued chased me. 

Meanwhile, Armstrong was attacking Felix, Malik, Alex, Mom, and Ender.Felix, Malek and Mom were flying their spaceships.  Alex and Ender were inside my base launching cannon balls. Armstrong hit the base with his Hypnotizer and everyone inside got hypnotized (Alex and Ender). Next he hit Mom and then Malek. Then in Felix's Fire Ship a slot openned to put the fireball shooter in. Felix did. Suddenly, a huge fireball shooter formed on top of Felix’s Fire Ship. Felix pressed the button and the fireball shooter shot a fireball. It hit the bad guys' spaceship, and it crashed, but Armstrong escaped. 

Meanwhile the bad guys were still chasing me. They were right above me and sucked me in with a tractor beam. 

"Oh no.” I said sadly.
